### PR TITLE
Added no harp line warning as red title on the plot

### PR DESCRIPTION
**Pull request by ZhixiaoSu**
This PR made two changes: 

1. When there's no harp clock detected, there will be error log in the printed output and also a red title on the harp line plot like this: harp_line_search
2. Save parameters in output file to enable potential debugging. 
`2024-07-31 11:30:17
Running generate_report.py with parameters:
  report_name: QC.pdf
  timestamp_alignment_method: harp
  original_timestamp_filename: original_timestamps.npy
  plot_drift_map: False
  flip_NIDAQ: False`

### CODE REVIEW

**Comment by ZhixiaoSu** [comment]
Hi @jsiegle and @alejoe91, this is ready for review. It's a few small fixes based on some recent feedbacks. One thing I'm not sure is: I had to hold the spikeinterface package to an older version to make sure the package works. For example, `se.get_neo_streams("openephys", directory)` won't work in lastest version in spikeinterface as 'openephys' is not one of the extensions. Maybe we can update the repo to be compatible to lastest version of spikeinterface later?

**Comment by alejoe91** [comment]
@ZhixiaoSu in the new version this has slightly changed: `openephys` should be `openephysbinary` (which is more precise ;))

**Review by alejoe91 — APPROVED** [review]
LGTM!

**Comment by ZhixiaoSu** [comment]
> LGTM!

Thank you! I'll upgade spikeinterface next time.

**Pull request merged**
